# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmE4OTk4MjAyZTA4MDgyOGY1OWU0OWU1MDBjMjNhNjUxNmNjYThjYTg5YzU4MGZhZTVhYTYxYmM2Y2Y1YzQ0YTYxYTAwMWVhNjc3NDllZTY5Mzc2MTI2N2QwYzU1YWY0ZmI2NzlhYTNkZTQ4OTE4MmUwODlkMTllNmZkN2VlOTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
